### ISSUE TITLE
/r/Android AppStore Slide Outs

### ISSUE THREAD

**Issue by GiiantWaffle** [d4rken/reddit-android-appstore#102]
Thanks for the App Store! :-)

This is not a "bug", per se, but sort of.

When a slide out is open, by tapping or swiping anything, like the 3-bar at the top left, or the pyramid at the top right, once something slides out (vertically or horizontally) and you tap the Back Arrow, it should close the Slide Out, not the app.

As you know, apps normally do it that way, so (no offense) it's kind of annoying to use it like you'd normally use an app and have it keep closing on you.

Thanks!

**Comment by bobheadxi** [comment]
Thanks for the feedback! Will get this fixed as part of #65 once we get around to it :)

**Comment by GiiantWaffle** [comment]
Thank you! :-)

**Comment by krissrex** [comment]
I have fixed this :) PR coming soon

**Comment by GiiantWaffle** [comment]
Thank You! :-)

Btw, just to mention it in case it's an issue (I haven't looked at it much, 'cause waiting for the update), could you please make sure that in the code, for when it lists apps (or anything) out, that it is set to "Ignore Case"?

Otherwise, apps that start with "aa" can end up being listed after "Zz", depending on Case.

"Ignore Case" is not Enabled by default in Android and so it ends up listing *not* alphabetically, as follows (please note caps and no caps):

ZZ
Aa
Za
aa

Yup!  That's actually how Android will list them out, if *not* all Names/Titles follow the "first letter upper case, second letter lower case" format.

Thanks Again! :-)

Dave
