### ISSUE TITLE
/r/Android AppStore - Check Boxes

### ISSUE THREAD

**Issue by GiiantWaffle** [d4rken/reddit-android-appstore#103]
When you tap on the pyramis on the top right (Filter icon?), the Check Boxes that appear do not work in combination.

For example, if you check; PHONE & FREE & PAID

...logically, you would think it would mean that you'd see all apps that are for Phones, whether Free or Paid, but *not* for Tablets, because you did *not* check that box.

But what happens, is that it only cares about the last box checked and ignores the others.  So since I checked them in the order shown above, it showed me Paid apps only and it showed me apps for both Phone and Tablet.

Without these functioning properly, it just makes looking through apps too much work, since you have to do it all over again for each one, or you're stuck scrolling through every single app.

Also, I don't recall seeing APPS & GAMES Check Boxes, to further refine it.  The labels in the left slide out don't help when trying to refine searches using the Filters.

**Comment by bobheadxi** [comment]
Thanks for pointing the issue with the checkboxes, will look into that!

As for a Apps and Games filter, would making the search restricted to whatever category from the left drawer the user is in a good alternative to a new filter? I.e. when in a subcategory of Games, hitting search could restrict the search to just apps in that subcategory

**Comment by GiiantWaffle** [comment]
Thank you for asking.

In my humble opinion, it wouldn't be intuitive to have to shift between the left slide out and the right slide out to accomplish one task, so I would have those boxes as Filters on the right as well.

What you could do with the ones on the left slide out (should you leave them there as well), is to have them show "All Apps" or "All Games", which I'm sure is what they do now. :-)

I.e., the ones on the left Slide Out would ignore the Filters (right word?) on the right Slide Out.

This is also why you should add "Apps" and "Games" Check Boxes on the right Slide Out.  Because the "Apps" and "Games" ones on ghe left should ignore the Filters on the right.

In my humble opinion, I think it would be very cool to set up a separate Check Box on the right that would be labeled, "Remember".  This would make it so that if checked, the app would remember the Filters that were applied when the app was closed.  Since lots of people will apply the same Filters 9 out of 10 times, it's a nice, convenient time saver that adds that little bit of extra polish to the app. :-)

But remember, tapping "Apps" or "Games" on the left always overrides the Filters!  If you want, rename the left items to "All Apps" & "All Games".  This will let users know right in the label that they ignore any set Filters (they shouldn't uncheck the Filters though).

They (Apps & Games) are handy to leave in there (left slide out), because if someone is looking for a specific app and maybe it was accidentally misfiled as a "TABLET" app and they have "PHONE" checked, then they will have the convenience of being able to open the left side, tap "All Apps" and be able to see for sure if you have the app or not (should it come to that).

This is why it is important to keep the ones on the left separate, as an "Override" function.  Then, if they want to go back to a Filtered View, they could just open up the right side again and tap "Refresh" (that should exist too).

Btw, did I mention in my other report about how anytime a Slide Out is open, the Back Arrow should close it and not the app?

Also, you may wish to consider a "Tap Back Arrow Twice to Exit" option, to prevent accidental app exits.  Those are so darn annoying!  Hahaha!

Please feel free to ask me any questions you'd like.  I do this for a living anyway (help Android develepors with app design, bug testing, test changes, write reports, make recommendations, help problem solve, write Docs, Helps, FAQ, etc.).  I'm sure I've worked on at least a couple of apps you know.  I think I've been succesful at it, because I'm thorough and I've always had a knack for seeing needs (in whatever type of scenario) that aren't normally thought of, but will occur and so they're already taken care of in the alpha and beta stages.

I'm not saying any of this to brag.  I'm letting you know what I do and that I'm good at it, because I'm offering my time to you free, because I'd like to use the app and these are the things that I genuinely believe will make it a better, more intuitive app and if you have anything that you'd like an outside, objective opinion on, or are looking for suggestions, I just wanted you to know that I'm available (no charge) and you can contact me directly if you ever wish to at:

giantwaffle AT zoho DOT com

I'm sure you know how to put the above address together. <lol>

Thank you again for your work! :-)

**Comment by bobheadxi** [comment]
@GiiantWaffle, I cannot seem to reproduce the issue you had with the filter checkboxes - PHONE & FREE & PAID cannot be simultaneously checked, because you can only choose one of either FREE or PAID. Being able to tick both would be the same as ticking neither, since an app is always either free or paid 😄 

> ...logically, you would think it would mean that you'd see all apps that are for Phones, whether Free or Paid, but not for Tablets, because you did not check that box.

Upon further consideration I believe this is the intended functionality: ticking PHONE indicates that you want all apps that are available for phones, regardless of whether or not they are compatible with tables. I think it makes sense: if I am looking for a WEAR app, for example, I would still want wear-compatible apps to show up even if they are compatible with different devices.

> But what happens, is that it only cares about the last box checked and ignores the others. So since I checked them in the order shown above, it showed me Paid apps only and it showed me apps for both Phone and Tablet.

Ticking PHONE, FREE and PAID will end up only selecting PHONE and PAID. All apps tagged PHONE and PAID will show up, including those tagged TABLET.

> This is also why you should add "Apps" and "Games" Check Boxes on the right Slide Out. Because the "Apps" and "Games" ones on ghe left should ignore the Filters on the right.

Not sure what you mean here - the idea is to use the left drawer to narrow down by category, then use the filters to find apps with specific traits. They are meant to be used in tandem, not ignore the other.

> In my humble opinion, I think it would be very cool to set up a separate Check Box on the right that would be labeled, "Remember". This would make it so that if checked, the app would remember the Filters that were applied when the app was closed. Since lots of people will apply the same Filters 9 out of 10 times, it's a nice, convenient time saver that adds that little bit of extra polish to the app. :-)

This would be a nice feature - I will open a new issue for it.

Also, just to reply to my own comment,
> As for a Apps and Games filter, would making the search restricted to whatever category from the left drawer the user is in a good alternative to a new filter? I.e. when in a subcategory of Games, hitting search could restrict the search to just apps in that subcategory

Looks like the app already does this! Handy.

Thank you for your feedback!
