### ISSUE TITLE
GlideModule Deprecation

### ISSUE THREAD

**Issue by bobheadxi** [d4rken/reddit-android-appstore#106]
`GlideModule`, implemented [here](https://github.com/bobheadxi/reddit-android-appstore/blob/750c2d624ca05721f53ca1912a8147afceae0346/app/src/main/java/subreddit/android/appstore/util/ui/glide/GlideConfigModule.java), appears to be slated for deprecation in [Glide v4](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/module/GlideModule.java)

Documentation of Glide v4’s new configuration method is [here](http://bumptech.github.io/glide/doc/migrating.html#configuration)

**Comment by krissrex** [comment]
Hi, found repo this on /r/Android. I can submit a PR for this soon.

**Comment by bobheadxi** [comment]
Thank you!
