### ISSUE TITLE
Reuse OkHttpClient instance

### ISSUE THREAD

**Issue by krissrex** [d4rken/reddit-android-appstore#116]
It is a best practice to create an `OkHttpClient` instance only once and then reuse it.
If new configuration is needed, use `client.newBuilder` on it [to share resources like thread pools](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html) (read the paragraph about customizing the client).

- [IconRequestModelLoader:119](https://github.com/d4rken/reddit-android-appstore/blob/815be90708cd3370e3abb8d91b039b7672f48721/app/src/main/java/subreddit/android/appstore/util/ui/glide/IconRequestModelLoader.java#L119)
- [LiveWikiRepository:31](https://github.com/d4rken/reddit-android-appstore/blob/a40705eb6645b5c7bcdfdbde0a149a2b79c73267/app/src/main/java/subreddit/android/appstore/backend/reddit/wiki/LiveWikiRepository.java#L31)
- [LiveWikiRepository:54](https://github.com/d4rken/reddit-android-appstore/blob/a40705eb6645b5c7bcdfdbde0a149a2b79c73267/app/src/main/java/subreddit/android/appstore/backend/reddit/wiki/LiveWikiRepository.java#L54)
- [GPlayScraper:26](https://github.com/d4rken/reddit-android-appstore/blob/815be90708cd3370e3abb8d91b039b7672f48721/app/src/main/java/subreddit/android/appstore/backend/scrapers/gplay/GPlayScraper.java#L26)
- [LiveGithubRepository:30](https://github.com/d4rken/reddit-android-appstore/blob/31500e5ba5e91d702fc707eab771dd11e7c04947/app/src/main/java/subreddit/android/appstore/backend/github/LiveGithubRepository.java#L30)
- [TokenRepository:55](https://github.com/d4rken/reddit-android-appstore/blob/815be90708cd3370e3abb8d91b039b7672f48721/app/src/main/java/subreddit/android/appstore/backend/reddit/TokenRepository.java#L55)

**Comment by bobheadxi** [comment]
Thank you for pointing this out, I will submit a PR for this
