### ISSUE TITLE
All strings should be translateable

### ISSUE THREAD

**Issue by airon90** [d4rken/reddit-android-appstore#134]
From #132:

> I believe these (the categories) are not included [into the translation file] because we pull them straight from the wiki, we don’t control what they’re called

Those strings should be considered in order to offer a complete localization of the app. The best choice is to offer the translation of the description of the app too. Is it possible to make those strings translateable?

**Comment by bobheadxi** [comment]
The category strings and the descriptions are pulled from the [r/Android wiki](https://www.reddit.com/r/android/wiki/apps), which is not maintained by us, but by the mods at the subreddit. Given its size, I doubt it will ever be updated with translations.

I’m sure somewhere there’s a library for automatically translating strings through services like Google Translate, but the translations will probably be less than ideal. With ~1000 apps the performance will likely be bad.

Unfortunately the best we can do is provide translations for the parts we can control.
