### ISSUE TITLE
New App Details screen doing all sorts of bad things

### ISSUE THREAD

**Issue by bobheadxi** [d4rken/reddit-android-appstore#142]
Relaunched android studio and now all subsequent builds have elements of AppDetails all over place, must have missed committing something in the PR????

- Title theme is wrong and positioned wrong
- FlowLayout disappeared
- Icon no longer centered

**Comment by d4rken** [comment]
Were you using "Instant Run"?

**Comment by bobheadxi** [comment]
Instant run is the little lightning button that doesn’t cause an app restart, right? I always just use the normal “Run” that restarts the app
