### ISSUE TITLE
Release v0.8.0

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#149]
- [x] Merge dev into master
- [x] Add version tag 
- [x] Create a draft release on github
- [x] Notify @d4rken when tag+draft release is created, to build a signed apk
- [x] Up the version in the dev branch

**Comment by bobheadxi** [comment]
Ah... i messed up the merging @_@

**Comment by d4rken** [comment]
What happened?

**Comment by bobheadxi** [comment]
Rebase merge made `master` deviate a lot from `dev`, says there is a ~20 commit difference now

**Comment by d4rken** [comment]
No worries.

Check [here](https://stackoverflow.com/questions/804115/when-do-you-use-git-rebase-instead-of-git-merge) for rebase vs merge.

Merging from dev into master is preferably done through a merge commit, not a rebase. Reserve rebase to update your own feature branches.

To fix this there are two options:

* Rewrite history by force pushing master and overwriting the changes. This is frowned upon in public repositories because it screws (conflicts galore) over anyone that has checked out the master branch already.
* Revert the commits and retry. This seems messy, but just costs us a bit spam in the log, and allows everyone who already cloned this repo to just pull the changes without conflict.

You already began the later option which is fine, though I think you also rebased them instead of merging them into master. Check the github button before pressing it 😉.

I'm now just merging the dev branch into the master again, I'll tag the final commit, build the apk and everything is in order.

To continue on dev with the next update I'll then pull the changes to master back into dev to get them to the same state.

**Comment by d4rken** [comment]
👍

**Comment by bobheadxi** [comment]
Ah, my bad 😢  thanks!

Given this is a fairly sizeable update any chance we might get a shoutout on the sub again for some installs? 🙋‍♂️
