### ISSUE TITLE
Execution failed for task ':app:compileMockDebugJavaWithJavac'

### ISSUE THREAD

**Issue by HElwy** [d4rken/reddit-android-appstore#155]
While trying to build the app I get the following error

> Error:Execution failed for task ':app:compileMockDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.MethodSpec$Builder.addJavadoc(Lcom/squareup/javapoet/CodeBlock;)Lcom/squareup/javapoet/MethodSpec$Builder;

**Comment by bobheadxi** [comment]
This might be caused by the change i made in #121, does removing the line added in that PR fix anything?

**Comment by HElwy** [comment]
I commented out the "compile 'com.squareup:javapoet:1.9.0'" line, but I'm still getting both errors

**Comment by bobheadxi** [comment]
Hm that's really odd, I just did a clean and rebuild myself and it compiled fine

**Comment by HElwy** [comment]
Excuse my noobishness, but shouldn't removing that line either change that error, such as this library is missing like in the GlideApp issue, or remove it entirely? Is there any class or library that relies on it?

**Comment by bobheadxi** [comment]
That line was a bit of a band-aid patch for an issue I encountered [here](https://github.com/d4rken/reddit-android-appstore/pull/115#issuecomment-320692924) - I don't think it should normally be included.

Could you try deleting your local copy of the repository and cloning it again? Unfortunately I can't seem to reproduce your issue

**Comment by HElwy** [comment]
Well, tried that but still didn't work out. I removed all glide and javapoet and then it worked, of course no graphics images, and all the apps are generic wear apps (1000 to be precise) and have lorem ipsum as content, I guess that is your current implementation not another bug specific for me..

**Comment by bobheadxi** [comment]
> removed all glide

Interesting that that works, does the app still look like in the screenshots on the README?

>  and all the apps are generic wear apps (1000 to be precise) and have lorem ipsum as content

That is the expected behaviour of the `mock` build. The `mock` build replaces things like Reddit and GitHub API calls with our own implementations for testing - in this case, a bunch of apps with no images and placeholder (loren ipsum) descriptions. You can switch to the `prod` build to see the live version

**Comment by HElwy** [comment]
> Interesting that that works, does the app still look like the screenshots on the README?

Yes, excluding the icons for each app

> That is the expected behaviour of the mock build.

Sorry, forgot about that, the prod-debug is working well, tried to return the code to its original state and building on a prod-debug setting, but still the same error unfortunately

**Comment by HElwy** [comment]
Changing the dagger version on the app from 2.9 to 2.11 fixed the issue for me, the app is working perfectly now.

**Comment by bobheadxi** [comment]
Thanks! 🎉 Ideally, we close the issue at the same time the PR is merged, but it doesnt matter that much
