### ISSUE TITLE
Stop refreshing data on returning to previous view

### ISSUE THREAD

**Issue by tranvietha2809** [d4rken/reddit-android-appstore#182]
For example, I am looking at a user's post history, found an interesting post after a lot of scrolling, click to read the comments. When pressing back to the last view, I have to scroll all over again to return to my last point of search.

**Comment by d4rken** [comment]
Not sure what you mean, can you share a few screenshots?

**Comment by tranvietha2809** [comment]
Hi d4rken this issue wasn't meant for this app. I got the wrong repository. Thank you for your prompt reply.
