### ISSUE TITLE
App listing not updated

### ISSUE THREAD

**Issue by Andrew-J-Larson** [d4rken/reddit-android-appstore#189]
My app on the Google Play store is at https://play.google.com/store/apps/details?id=aliendrew.ms.stickynotes ... Yet on the /r/Android App Store, it's not updated at all, with it's old name and no graphics from the Play Store. The app on the /r/Android...Store is currently named "Microsoft Sticky Notes {Unofficial}" when it should be "Unofficial Sticky Notes"

**Comment by d4rken** [comment]
This app parses the /r/Android wiki, you'll have to ask the mods there to update your entry.

**Comment by Andrew-J-Larson** [comment]
I did that and then they told me to come here smh...

**Comment by bobheadxi** [comment]
FYI it's here: https://www.reddit.com/r/android/wiki/apps (search for `Microsoft Sticky Notes {Unofficial}`)
