### ISSUE TITLE
Add all the categories from the wiki to the content navigation view

### ISSUE THREAD

**Issue by garretyoder** [d4rken/reddit-android-appstore#26]
Wiki now has new categories, move **all** filters out of the filter menu and into the navigation drawer, behind two categories, Apps and Games

**Comment by d4rken** [comment]
See:
https://github.com/d4rken/reddit-android-appstore/blob/master/app/src/main/java/subreddit/android/appstore/screens/navigation/NavigationFragment.java#L80
The callback should take the data it supplies and update the navigation from it.

**Comment by d4rken** [comment]
Use this to create filtered app lists:
https://github.com/d4rken/reddit-android-appstore/blob/master/app/src/main/java/subreddit/android/appstore/screens/list/AppListFragment.java#L64
