### ISSUE TITLE
Getting icons and screenshots

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#39]
Thoughts
* App data from the wiki gives us a target from which to scrape the urls for icons and screenshots
* As it's a resource intensive operation we should only get the media for apps we are actually viewing
* Glide will trigger a load request for list items that are display or details pages being opened
* Glide needs the URLs obtained through scraping
* Glide can't to the scraping because the scraping returns multiple relevant values that may be needed in other requests (e.g. one icon load request, multiple screenshot load requests)
* UX may cause multiple requests for the the same media

Sequence
* Icon ImageView becomes visible
* Glide does something like `load(new AppIconRequest(appInfo))`
* Glide has to first resolve the `AppInfo` item a `ScrapeResult`
* Glide asks a `TargetScraper` for the data
* The TargetScraper scrapes the target ensures there is at most one request per item and caches the scrape result
* Glide uses the scraped urls to load the images and caches them

Responsibilities
* Glides caches the Bitmaps
* TargetScraper caches the ScrapeResults
* WikiRepository caches the AppInfos

Issues
* There is an unknown amount of screenshots to load
* We could give glide a viewpager target that can be filled with an arbitrary amount of screenshots instead of manually initiating a load request per known screenshot and adding it to a viewpager?

**Comment by dragnu5** [comment]
Where will the images be hosted?

Or is it directly from the Google Play store?

If it's hosted elsewhere, having them as WEBP would be great as it uses much less data and useful to us with low data caps.

**Comment by d4rken** [comment]
@dragnu5 The app will try to get the images from the apps download page which in most cases will be Google Play. I think most of them are .pngs

Example:
http://lh4.ggpht.com/mJy7ntNeprYHRqIVF7vXfDwQ6lFe8yDgB5NWd3bcTDTLAOn1jh6DavG8Fnjejw4RqSWz=w300

**Comment by d4rken** [comment]
@dragnu5 See: 5cd6b11662969c81f61f62ca655d87c9d42a323e
Icons are now loaded specifically for target imageviews, meaning we directly get the desired icon size from Google Play not wasting any extra bytes :grin:

**Comment by garretyoder** [comment]
See #40, implemented. Closing.
