### ISSUE TITLE
App crashes when server is unavailable.

### ISSUE THREAD

**Issue by dragnu5** [d4rken/reddit-android-appstore#42]
When the server is unavailable (like blocked in my country) the app will crash rather than displaying an error message.

**Comment by d4rken** [comment]
Can you post a stacktrace?

**Comment by Flippylosaurus** [comment]
Will try to reproduce and post a stack trace if possible.

**Comment by garretyoder** [comment]
If you have a stacktrace we can fix it, I'll also try to reproduce.

**Comment by dragnu5** [comment]
Here's a logcat from when I launched the application.


http://pastebin.com/0zvWx7pU

I tried launching the app without having an internet connection, and it crashes instantly. That should be much easier to reproduce.

**Comment by Flippylosaurus** [comment]
Can confirm - mine says about the same.

**Comment by garretyoder** [comment]
Working on it right now, should have it fixed shortly here, thanks for the stacktrace guys!
