### ISSUE TITLE
Changelog dialog

### ISSUE THREAD

**Issue by garretyoder** [d4rken/reddit-android-appstore#44]
Display a changelog dialog informing the user on what is new when a new version of the app is started for the first time.

**Comment by d4rken** [comment]
Data could be pulled from github releases.

**Comment by avipars** [comment]
I did this for my own app a while ago. It gets to be a pain in the ass to update it, so unless you have it work automatically, it's not worth your time.

**Comment by bobheadxi** [comment]
Implemented, https://github.com/d4rken/reddit-android-appstore/pull/95
