### ISSUE TITLE
What is "Leaks"?

### ISSUE THREAD

**Issue by Flippylosaurus** [d4rken/reddit-android-appstore#47]
App creates a icon in the app drawer called "Leaks". FC's on startup.

Explanation is welcome.

**Comment by garretyoder** [comment]
Did you build it yourself, or download the official build? The "Leaks" icon is a debugging library we use called LeakCanary (https://github.com/square/leakcanary)
On official builds grabbed from the release page, it is disabled. 
Leakcanary is only enabled on debug builds if you built it yourself.
