### ISSUE TITLE
AMOLED theme causes screen artefacts

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#48]
Nexus 5 @ 6.0.1
Build from commit 47209cc577ef520be2bd8ed189939bb04093e14b

![2016-09-12 01 58 06](https://cloud.githubusercontent.com/assets/1439229/18422572/46cc024c-789d-11e6-92e8-852a166f2362.png)

**Comment by d4rken** [comment]
![2016-09-12 02 18 32](https://cloud.githubusercontent.com/assets/1439229/18422871/fd13577e-789f-11e6-8b48-0171e1a7dc74.png)

**Comment by garretyoder** [comment]
This is garbage coming from the CPU due to android misinterpreting default transparency values and trying to blend the activity with itself. Wish I was joking. 
ba879b2 may possibly fix, needs testing

**Comment by d4rken** [comment]
Unfortunately not.

![2016-09-12 18 20 09](https://cloud.githubusercontent.com/assets/1439229/18447327/6bebbfe8-7926-11e6-9b6a-67ab0fc09c6c.png)

**Comment by garretyoder** [comment]
Well, looks like I have some testing to do haha.

**Comment by garretyoder** [comment]
66b13c4 possible fix, needs testing.

**Comment by d4rken** [comment]
Nope.
![2016-09-14 19 33 27](https://cloud.githubusercontent.com/assets/1439229/18526952/f50b403a-7ac2-11e6-8a70-039eb5b49195.png)
