### ISSUE TITLE
Wrong dialog theme

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#49]
Note4 @ 5.0.1
Build from bef46209d8c3e3a921e49187c507a28c224b6dc1
Dialog accent color is wrong.

![device-2016-09-12-042216](https://cloud.githubusercontent.com/assets/1439229/18422931/9f6214fc-78a0-11e6-8f0b-cf3563a3b2e5.png)

**Comment by drivfe** [comment]
Also, typo

**Comment by drivfe** [comment]
Seems like a framework/AlertDialog bug? Works fine on M and N.

**Comment by d4rken** [comment]
Likely is.
I think switching to Support Preference Fragments would fix it.
