### ISSUE TITLE
Retrolambda?

### ISSUE THREAD

**Issue by drivfe** [d4rken/reddit-android-appstore#55]
Could help clean the code up a bit

**Comment by d4rken** [comment]
How stable is retrolambda?
AFAIK it's bit of a hacky way of introducing lambdas?
Any known issues?

Never used it before, but I'm not against trying it here. What would have to be done to introduce it here?

**Comment by drivfe** [comment]
Check this: https://www.reddit.com/r/androiddev/comments/45j7zn/retrolambda_just_a_hack/czyakcq

Setup:
Project's build.gradle: ```classpath 'me.tatarka:gradle-retrolambda:3.2.5'````

Module's build.gradle: ```apply plugin: 'me.tatarka.retrolambda'```

and
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by d4rken** [comment]
This would make the rxjava chains nicer looking, right?

Sounds good, will you make a PR ? :grin:

**Comment by drivfe** [comment]
Yes, I'll do a PR when I have some time tonight.
