### ISSUE TITLE
Report Dialog layout

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#66]
The report dialog has weird padding.

**Comment by MiguelLarios** [comment]
I recommend using MaterialDialogs library for this cases. It is easier.

**Comment by Pika3323** [comment]
Why not just use an AlertDialog?

**Comment by MiguelLarios** [comment]
He is currently using a custom class that extends Dialog to show the report Dialog. It has a message and an EditText. Being honest I see more convenient to do just:
```java
new MaterialDialog.Builder(this)
        .title(R.string.input)
        .content(R.string.input_content)
        .inputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD)
        .input(R.string.input_hint, R.string.input_prefill, new MaterialDialog.InputCallback() {
            @Override
            public void onInput(MaterialDialog dialog, CharSequence input) {
                // Do something
            }
        }).show();
```

It has its own callback and you can call your action from there.

At the end it is just my own opinion, and I am not saying it is wrong or something as it is.

**Comment by garretyoder** [comment]
Material dialogs is a big of overkill, it's a fantastic library, used it on many a occasion, but for one dialog a entire library is a tad overkill. I'll reformat the dialog to stay more in line with system dialogs, though.
