### ISSUE TITLE
not working without playstore

### ISSUE THREAD

**Issue by treakiandroid** [d4rken/reddit-android-appstore#71]
hi,

i have got the app from fdroid and it seams to be not working without playstore which i dont have and dont want.

could you change it to directly download apks or show only apps avivable in fdroid repository.

or maybe create a own fdroid repository for it?

thanks

**Comment by garretyoder** [comment]
The app pulls all of its data from r/Android's wiki. Nearly all of their apps, are play store apps. There isn't anything we can do about that, sorry.

**Comment by wolfkin** [comment]
If we changed the Wiki links from PlayStore to APKMirror (where applicable) would that change this behaviour?

**Comment by d4rken** [comment]
@wolfkin APK mirror doesn't provide screenshots, while Google Play does.

**Comment by wolfkin** [comment]
understood. Thanks.
