### ISSUE TITLE
Detect Wiki Revisions to Provide Users a list of New Apps/Games

### ISSUE THREAD

**Issue by IAmAN00bie** [d4rken/reddit-android-appstore#73]
With the app featuring close to 1,000 apps, it will be pretty difficult for new users to find what apps were recently added. I propose using the Reddit API to parse the revision history (possibly the past 3-5 revisions) and create a new category in the app to list these apps that have been added (altogether in one table, no need to separate these "newly added" apps into subcategories.)

https://www.reddit.com/dev/api/oauth#scope_wikiread

Relevant GET request: https://puu.sh/rB7d3/ec33617240.png

Since this request does not require a mod hash, this should be accessible by any person using the app.

**Comment by d4rken** [comment]
Backend idea:
* Get the last X revisions
* Parse for app names in revision difference
* Tag using app names as identifiers tag`AppInfo`objects as recently modified

UI ideas:
* Have the navigation presenter generate an entry called `New` at the top of the list.
* Modify the `CategoryFilter` class to support this tag
* Modify the ListPresenter to support this new filter tag

**Comment by bobheadxi** [comment]
I am going to try and work on this

**Comment by IAmAN00bie** [comment]
We would greatly appreciate it ;)

**Comment by bobheadxi** [comment]
Done: https://github.com/d4rken/reddit-android-appstore/pull/92
What do you think @d4rken

**Comment by d4rken** [comment]
Implemented by @bobheadxi in #92
