### ISSUE TITLE
Deal with markdown in descriptions

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#8]
Parse description data better, see if we can pull more information (possibly tags) from it:
https://github.com/d4rken/reddit-android-appstore/blob/36e4daaa4a1f9969917c3fc3833213d68c684bf4/app/src/main/java/subreddit/android/appstore/backend/BodyParser.java#L169

Add tests to confirm it works:
https://github.com/d4rken/reddit-android-appstore/blob/master/app/src/test/java/subreddit/android/appstore/backend/WikiRepositoryTest.java

**Comment by plays2** [comment]
I'm assuming you mean parse the description to auto-index/categorize the apps? Based on buzz words like 'music' or 'social'? If so, I'm about to start doing that.

**Comment by garretyoder** [comment]
Take a look at the wiki again before you do that, the r/Android mod was kind enough to spend some time organizing the wiki for us last night.

Also, we're about to reorganize the app list into two categories, Games and Apps

**Comment by d4rken** [comment]
I was thinking about dealing with markdown syntax, e.g. links in the text.

Am 07.09.2016 8:29 nachm. schrieb "Garret Yoder" <notifications@github.com>:

**Comment by d4rken** [comment]
See:
https://github.com/d4rken/reddit-android-appstore/blob/master/app/src/main/java/subreddit/android/appstore/backend/parser/DescriptionColumnParser.java

One idea would be to translate the markdown to html tags which we can then display in a _clickable_ way in a `TextView`-

**Comment by d4rken** [comment]
This translate markdown to html:
https://github.com/commonsguy/cwac-anddown
This just takes markdown and displays it:
https://github.com/falnatsheh/MarkdownView

**Comment by bobheadxi** [comment]
@d4rken From just skimming through the wiki it seems like only two types of markdown are used in the descriptions: bold and links. Would it be a better idea to just handle them manually in `DescriptionColumnParser`?

**Comment by d4rken** [comment]
Maybe make a module that internally does it manually for those two cases for now and can later be replaced with more extensive operations if necessary.
