### ISSUE TITLE
Add a link for developers

### ISSUE THREAD

**Issue by avipars** [d4rken/reddit-android-appstore#83]
I am a developer and would like to add my app to your wiki, can you add the request URL to the description here?

**Comment by d4rken** [comment]
We only parse the reddit wiki, you have to request it there, when it's added, it will automatically appear here.

**Comment by avipars** [comment]
That's cool. Is it in JSON? 

Can you just put the link in the overflow menu? 
And I meant initially, the readme file. 

https://androidflair.github.io/wikiapps/

**Comment by d4rken** [comment]
It's not JSON, its markdown that the app parses.

You're a dev, feel free to submit a pullrequest :wink: .

**Comment by avipars** [comment]
Pull request to the dev branch?

**Comment by geekodour** [comment]
cool
