### ISSUE TITLE
Change sorting order

### ISSUE THREAD

**Issue by cauebs** [d4rken/reddit-android-appstore#86]
At the moment apps are always sorted alphabetically, so I'd suggest some other method(s) that are more dynamic and, therefore, less biased. Perhaps a mix of popular and recently updated to mix things up.

**Comment by d4rken** [comment]
How?
We don't have any information about what is popular or what has been updated.

**Comment by cauebs** [comment]
Yeah, I understand. But it is possible. For popularity, you could count clicks. For recently updated, well, that's more complicated still and I can only think of scraping :/

But I'm only suggesting because it would really improve the overall experience :)

**Comment by d4rken** [comment]
Counting clicks across users would require a server and that is not really within the scope of this project.
