### ISSUE TITLE
Testing v0.7.0

### ISSUE THREAD

**Issue by d4rken** [d4rken/reddit-android-appstore#96]
> Is the current dev branch ready for release?

- [x] Open each page
- [x] Check functionality on each page
- [x] Rotate the device on each page
- [x] Enable don't keep activities in developer settings, open each page, press the home button, open the app again from recents

**Comment by bobheadxi** [comment]
Everything works fine, except for a few things:
- bug in the update checker #97, I don't really understand how the user interceptor stuff works yet but I can look into it - if you could provide a bit of insight into how it works that would help a lot :) Should probably fix this one before release
- cosmetic issue #98, not really critical
- memory leaks: leakcanary keeps reporting leaks, but it doesn't seem to cause any issue when actually using the app, not sure if I should look into it more

**Comment by bobheadxi** [comment]
All's good, I think we're ready to go

**Comment by d4rken** [comment]
I'll make a signed build when I'm later at home.

**Comment by d4rken** [comment]
https://github.com/d4rken/reddit-android-appstore/releases/tag/v0.7.0

@bobheadxi Can write a few points into the release description about what's new?

**Comment by bobheadxi** [comment]
Yep, done! Also of note, seems that Travis is failing? Is that of any concern?

**Comment by d4rken** [comment]
I need to remember to update the travis config, especially when making changes to the apps build config. Thanks for the headsup.
